name: galeri_lukisan
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  carousel_slider: ^4.0.0
  country_code_picker: ^2.0.2
  http: ^0.13.4
  provider: ^6.0.5
  dio: ^5.0.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets:
  - assets/icons/
  - assets/images/
  uses-material-design: true

